version: "3.9"
services:
  # web:
  #   image: django-k8:v1
  #   depends_on:
  #     - postgres_db
  #   build:
  #     context: ./django
  #     dockerfile: Dockerfile
  #   environment:
  #     - PORT=8020
  #   env_file:
  #     - django/.env
  #   ports:
  #     - "8001:8020"
  #   command: sh -c "cd /app && chmod +x ./migrate.sh && sh ./migrate.sh && ./entrypoint.sh"
  #   # volumes:
  #   #   - staticfiles:/app/staticfiles/
  postgres_db:
    image: postgres
    restart: always
    command: -p 5433
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    env_file:
      - django/.env
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis_db:
    image: redis
    restart: always
    ports:
      - "6380:6380"
    volumes:
        - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6380


volumes:
  # staticfiles:
  #     external: true
  postgres_data:
  redis_data: