name: Build docker container & push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_djagno_job:
    uses: akhil7philip/django_kubernetes/.github/workflows/test_django.yml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_djagno_job]
    env:
      DJANGO_SECRET_KEY: set_one_better
      CLUSTER_NAME: dj-k8-cluster
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: login to DO Container Registry
      run: doctl registry login --expiry-seconds 1200
    - name: build container image
      working-directory: ./django
      run: |
        docker build \
        -t registry.digitalocean.com/aks-dj-k8s/django_kubernetes:latest \
        -t registry.digitalocean.com/aks-dj-k8s/django_kubernetes:${GITHUB_SHA::7} \
        -f Dockerfile .
    - name: push image
      run: |
        docker push registry.digitalocean.com/aks-dj-k8s/django_kubernetes --all-tags
    - name: k8 cluster kube config file
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
    - name: update deployment secrets
      run: |
        cat << EOF >> django/.env.prod
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
        DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
        DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
        DB_NAME=${{ secrets.DB_NAME }}
        DB_USERNAME=${{ secrets.DB_USERNAME }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DB_HOST=${{ secrets.DB_HOST }}
        DB_PORT=${{ secrets.DB_PORT }}
        EOF
        kubectl delete secret django-k8s-prod-env
        kubectl create secret generic django-k8s-prod-env --from-env-file=web/.env.prod
    - name: update deployment image
      run: |
        kubectl set image deployment/django-deployment django-deployment=registry.digitalocean.com/aks-dj-k8s/django_kubernetes:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/django-deployment
    - name: Post-build Django Commands - Migrate / Collectstatic
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l app=django-deployment -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/collectstatic.sh