name: Rollout Django Deployment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rollout:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: dj-k8-cluster
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: insall doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: k8 cluster kube config file
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: run rollout on Deployment
        run: |
          kubectl rollout restart deployment/django-deployment